language: node_js
node_js:
- '6.10'
install: npm install
script: npm test
before_deploy: echo 'All unit tests passed; Successfull built distribution assets;
  Preparing to deploy Discovery-API to AWS.'
deploy:
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_DEVELOPMENT"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_DEVELOPMENT"
  region: us-east-1
  app: discovery-api
  env: discovery-api-dev
  bucket_name: elasticbeanstalk-us-east-1-224280085904
  bucket_path: discovery-api-dev
  on:
    repo: NYPL-discovery/discovery-api
    branch: development
after_deploy: echo 'Successfully executed deploy trigger for Discovery API'
notifications:
  slack:
    secure: g6eiX6ALpd0VvGsSCDyCGpwtkvTT3qDcNTwXFK7yj85y4ZaRPUHqV22RXUn+7hyvPDbaXM1o61Q5EwBCC3XGlzirqGoM0l22TDQq3ZchtJGTSFrALcWGHaj6YHCQOyHu4TbFsaYGzMNG0o2DVjC2A1L/psoLVj5S0mQXtRmsWNiBAfff4kqOBYk76459rCkAGoUkV5Wwz6D0XPdLxVFmOqtfFdt427jjZcQp9tj5as9B33ERm4kdIKX2/CXdJE3F7+YjKeyrUhrqggLRJiTBKc53reoy8X26QjExfQ95ewPkdHx+CAnXKhW1TLym4+EpRTSrQIFt2dhKvT+0VU4X3XIKlxTn2KA/UX/1Qln6s8SMRqzeaNqB6t8rckzqQ3NN5HSgHmcERnmwFaRM4mPfxwTf5RR0bnoZd4iq7x3hiznztLJp3S5i1hUQCm8IJ83sTEU9LHsVdaaBjTOk7FAtATGX3IGA86BKVvdpULgQFaucAx5jRXIGyRFqcuzka3B4UYSyfatU3i+KRVDIuo+PkbcsjLL7EGT3fPZVeXgXnxdLQT7s9mKtEMhCDGOzH4gApJJn62Z+x0m3hoUgR8Y5sw9o9yoiwD2ldlQtYQ/1iMP/mku3gyF8nsCe9AR3nMmUJGyCufEBOTR8A6THscINRU/4pVxWfdFDAUjz1qoADKM=
env:
  global:
  - secure: SuUN9LkkghW8/bxfg03wDrAgiC75mExz+vdmovAbrEY8vBgX1cQmb+6eTj5pYj8SC/vt9ujFuRMShvUk5EuT76N2p8DOfMJDvZRAcB5bu8e4vMjFduNKgMt9unNrEPbm0LUbm1IN7kBGqI/l38Gg6w5x1Xq3TC2esR5GutALEjeP2iuSnjPfORUOOsq+Fo6Ce+wJ6rE7ZqCHIrd1Y6QJqlOKCbA7FaEEFeibEJMg9Y3+va1Bek3vNUW5NkuIyScx41XJZySxIvkakvFk9dVs/abctN+XuRFO9u2jLu+vff+XgxyuuzZ5dI4nUwd+P9QVevM41GVwAlbv/CY+jj2RGhU4tG/Emskapwl1oakmxHXWTty0nBKEdaFZoHBWDr27Wzk2UQdIAVq7V3bRUZlghl1NyY/cgv2DB/5m4gKX4hQga5O5E3gxD1tFCgsK5ifWydjRnukNOb0XTAUtIRI+4v53HksPFHOOl57Kekhv7I1VOvOiWr3q1+2hMsjNjcmXZKQXsLqlTvxFeeFrrTnpR+UHnoKS1uCL2lEO7k6Lw/z5XQezzFS0Ayxu8SWN9adjAtKig7ug8s656VVAnsgpo7Ohd4i3lA3LQOO3Cr79iC7ridcmzrU1FcYArxj88kPcSX/aXCsD5Ln1HlAStuinM1Rpao17tpsHA651sCXih2I=
  - secure: Rh8rWJz5qfX25G9RAQwQJcIRBM5K118kKF1V6gtN9ih6/CSG+kvds2yJP+yo5dKPJtga2w4IH7eFDUEetsm81TPcFnLAcoWn6t2Tc9ouCggCASYi34wM9B8XbTmxljNLIAQiam+Y/y/oDUad7/3VUdq3MqLzy5/Bc5Fgw3zXseOmCoSbc2GCpADDxPWX7UyPxMOcXO09mzow4E2+zWcMyKnfgbL7wPndajti5zGFNolfj4S3jW9Oq5fR7qXA8mzR+CEC9g3Jzj9PO3Uf9zY6PWeEEEkh+UpkyEqqdxprUxCjWZo7ZenEUETtqkifcakQ59ZKx6LNqJRpcrNu+nlcSLco4/CsxM10Hfk09VJtgK1/zfHVfU0/lLplbEho33C6ImuCLL6TxwpPyd5uP7yyJ2OD7rwRM09TKVdamfzUYioPQ4TMkK5KCpjKJJ5D2QixKQsncAMHpqSb3gFP9Nbs1ePC+9IYZK0lBbKwY014Di6IgYwn8xMwQUW48hyqvIgZrZZ+FtSQgZYUhltdAE/2sL5tGOir8ANGbra5DUjWJdw2vaElcMmYht3c0OnRAhogxEk2usNAy9ZHCmkHHgovTZXZ96XJXnk6uWaybIRdaqjpOH2iD3zh9L05XQCOZwHfqfJC/RX9wFRSZr/3bWIIJnnAd2eQn5LcVUgIYlkHLE0=
